name: StoryEngine
author: balzikz
main: balzikz\storyengine\Main
version: 2.1.0-alpha
api: [5.0.0]
description: "Движок для создания интерактивных историй"

permissions:
  storyengine.command.admin:
    description: "Дает полный доступ к командам StoryEngine"
    default: op
commands:
  story:
    description: "Главная команда StoryEngine"
    permission: storyengine.command.admin
