name: Build Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: gd, pmmp, sqlite3
          tools: composer

      - name: Download Box
        run: wget https://github.com/box-project/box/releases/latest/download/box.phar -O box.phar && chmod +x box.phar

      - name: Build PHAR
        run: ./box.phar compile

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: StoryEngine.phar
          path: StoryEngine.phar
