name: See The Truth

on:
  push:
    branches: [ "main" ]

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show me everything
        run: ls -R
