name: Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Plugin
        id: poggit
        uses: poggit/poggit-ci@v4 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: StoryEngine.phar
          path: ${{ steps.poggit.outputs.artifact_path }}
